###############################################################################
## Configuration file
## Drone name: munchkin
## Date: 13 February 2020
## Tuning:
## -fsf: no
## -se : no
###############################################################################
ctrl_freq: 100

fsf_x_P: 0.88
fsf_x_S: 1.3
fsf_y_P: 0.88
fsf_y_S: 1.3
fsf_z_P: 0.90
fsf_z_S: 1.34

use_StatesObserver: false

se_x_Lpos: 0.9
se_y_Lpos: 0.9
se_z_Lpos: 0.9
se_x_Lspeed: 4.1
se_y_Lspeed: 4.1
se_z_Lspeed: 4.1
se_x_Lunc: 8.3
se_y_Lunc: 8.3
se_z_Lunc: 8.3

se_x_Filter: 0.9
se_y_Filter: 0.9
se_z_Filter: 0.15

mass: 1.1
hoverCompensation: 0.33
maxAngle: 45.0
maxVerticalAcceleration: 4.0
